server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/csOverflow
    username: root
    password: 9213124136SS

jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update


file:
  storage:
    location: fileStorage